### ISSUE TITLE
building libwebrtc library for android fails

### ISSUE THREAD

**Issue by tku11** [open-webrtc-toolkit/owt-client-native#229]
Hi,

trying to build libwebrtc library for android. After finishing gclient sync the next step
(scripts/build_android.py) fails:

~/owt-client-native/src$ sudo python ./scripts/build_android.py

> args: Namespace(debug=False, output_path='/home/timo/owt-client-native/src/out', target_arch='arm,arm64,x86')

> generating args for arm release
Traceback (most recent call last):
  File "./scripts/build_android.py", line 98, in <module>
    gn_gen(arch, options.debug)
  File "./scripts/build_android.py", line 28, in gn_gen
    if subprocess.call(cmd) :
  File "/usr/lib/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Working on Ubuntu 16.04 in VirtualBox, openssl and depot tools are installed.
Help is really appreciated as I'm new to native webrtc and a bit lost

**Comment by jianjunz** [comment]
@zhangyihui1, any idea?

**Comment by zhangyihui1** [comment]
Do you use master source code ? please use branch 4.2.x for Android build

**Comment by Jackoder** [comment]
```sh
root@jackoder-virtual-machine:/home/jackoder/video/owt-client-native# python ./scripts/build_android.py 

> args: Namespace(debug=False, output_path='/home/jackoder/video/owt-client-native/out', target_arch='arm,arm64,x86')

> generating args for arm release
Traceback (most recent call last):
  File "./scripts/build_android.py", line 98, in <module>
    gn_gen(arch, options.debug)
  File "./scripts/build_android.py", line 28, in gn_gen
    if subprocess.call(cmd) :
  File "/usr/lib/python2.7/subprocess.py", line 493, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1249, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
root@jackoder-virtual-machine:/home/jackoder/video/owt-client-native# git status
# On branch 4.2.x
# Untracked files:
#   (use "git add <file>..." to include in what will be committed)
#
#	.cipd/
#	.gclient
#	.gclient_entries
#	.gclient~
#	src/
nothing added to commit but untracked files present (use "git add" to track)
root@jackoder-virtual-machine:/home/jackoder/video/owt-client-native# 

```

I'm using the branch 4.2.x and get the same error

**Comment by Jackoder** [comment]
add the depot_tools to PATH, it resolved
