### ISSUE TITLE
 gclient sync Faild！！！

### ISSUE THREAD

**Issue by liubin123456** [open-webrtc-toolkit/owt-client-native#305]
This is my error：
src (ERROR)
----------------------------------------
[0:00:00] Started.
----------------------------------------
Traceback (most recent call last):
  File "D:\Working\soft\depot_tools\metrics.py", line 267, in print_notice_and_exit
    yield
  File "D:\Working\soft\depot_tools\gclient.py", line 3182, in <module>
    sys.exit(main(sys.argv[1:]))
  File "D:\Working\soft\depot_tools\gclient.py", line 3168, in main
    return dispatcher.execute(OptionParser(), argv)
  File "D:\Working\soft\depot_tools\subcommand.py", line 252, in execute
    return command(parser, args[1:])
  File "D:\Working\soft\depot_tools\gclient.py", line 2725, in CMDsync
    ret = client.RunOnDeps('update', args)
  File "D:\Working\soft\depot_tools\gclient.py", line 1763, in RunOnDeps
    patch_refs=patch_refs, target_branches=target_branches)
  File "D:\Working\soft\depot_tools\gclient_utils.py", line 906, in flush
    reraise(e[0], e[1], e[2])
  File "D:\Working\soft\depot_tools\gclient_utils.py", line 983, in run
    self.item.run(*self.args, **self.kwargs)
  File "D:\Working\soft\depot_tools\gclient.py", line 933, in run
    file_list)
  File "D:\Working\soft\depot_tools\gclient_scm.py", line 132, in RunCommand
    return getattr(self, command)(options, args, file_list)
  File "D:\Working\soft\depot_tools\gclient_scm.py", line 516, in update
    mirror = self._GetMirror(url, options, revision_ref)
  File "D:\Working\soft\depot_tools\gclient_scm.py", line 957, in _GetMirror
    if not self.cache_dir:
  File "D:\Working\soft\depot_tools\gclient_scm.py", line 218, in cache_dir
    return git_cache.Mirror.GetCachePath()
  File "D:\Working\soft\depot_tools\git_cache.py", line 304, in GetCachePath
    ['cache.cachepath']).strip()
  File "D:\Working\Python27\lib\subprocess.py", line 530, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "D:\Working\Python27\lib\subprocess.py", line 672, in __init__
    errread, errwrite)
  File "D:\Working\Python27\lib\subprocess.py", line 882, in _execute_child
    startupinfo)
WindowsError: [Error 2]

**Comment by kefan-hu** [comment]
I have same  problems

**Comment by yinwuju202006** [comment]
I have same problems too

**Comment by windboy12138** [comment]
I have same problems too，I print executable para in _execute_child，it's value is None，so it's failed.
I try to use Powershell to run gclient sync it's worked, but failed to build.
