### ISSUE TITLE
windows client build error

### ISSUE THREAD

**Issue by Kmtest-rgb** [open-webrtc-toolkit/owt-client-native#388]
Hi
 I'm getting the following error when I start the build script 

python build-win.py --gn_gen --sdk --tests --ssl_root C:\Users\mmm\owt_win_client --msdk_root "C:\Program Files (x86)\IntelSWTools\Intel(R) Media SDK 2020 R1\Software Development Kit" --arch x64 --output_path C:\Users\muthsh01\owt_win_client\src\out
Namespace(arch='x64', docs=False, gn_gen=True, msdk_root='C:\\Program Files (x86)\\IntelSWTools\\Intel(R) Media SDK 2020 R1\\Software Development Kit', output_path='C:\\Users\\muthsh01\\owt_win_client\\src\\out', scheme='debug', sdk=True, ssl_root='C:\\Users\\muthsh01\\owt_win_client', tests=True)
Traceback (most recent call last):
  File "C:/Users/mmm/owt_win_client/src/build/vs_toolchain.py", line 561, in <module>
    sys.exit(main())
  File "C:/Users/mmm/owt_win_client/src/build/vs_toolchain.py", line 557, in main
    return commands[sys.argv[1]](*sys.argv[2:])
  File "C:/Users/mmm/owt_win_client/src/build/vs_toolchain.py", line 373, in CopyDlls
    _CopyRuntime(target_dir, runtime_dir, target_cpu, debug=True)
  File "C:/Users/mmm/owt_win_client/src/build/vs_toolchain.py", line 345, in _CopyRuntime
    _CopyUCRTRuntime(target_dir, source_dir, target_cpu, '%s140' + suffix,
  File "C:/Users/mmm/owt_win_client/src/build/vs_toolchain.py", line 297, in _CopyUCRTRuntime
    _SortByHighestVersionNumberFirst(sdk_bin_sub_dirs)
  File "C:/Users/mmm/owt_win_client/src/build/vs_toolchain.py", line 238, in _SortByHighestVersionNumberFirst
    list_of_str_versions.sort(key=to_number_sequence, reverse=True)
TypeError: '<' not supported between instances of 'int' and 'str'
ERROR at //build/toolchain/win/BUILD.gn:49:3: Script returned non-zero exit code.
  exec_script("../../vs_toolchain.py",
  ^----------
Current dir: C:/Users/mmm/owt_win_client/src/out/debug-x64/
Command: C:/Users/mmm/AppData/Local/Programs/Python/Python38/python.exe C:/Users/muthsh01/owt_win_client/src/build/vs_toolchain.py copy_dlls C:/Users/mmm/owt_win_client/src/out/debug-x64 Debug x64
Returned 1.
See //BUILD.gn:5:1: which caused the file to be included.
group("default") {

---------------------------------

seems to be a python version issue ??

python --version
Python 3.8.4

Appreciate any help .

thanks

**Comment by taste1981** [comment]
@Kmtest-rgb make sure DEPOT_TOOLS_WIN_TOOLCHAIN env variable is set to 0; and also remove python installation by yourself from the path.
