### ISSUE TITLE
owt client native android build failed.

### ISSUE THREAD

**Issue by bobbiFr** [open-webrtc-toolkit/owt-client-native#402]
Hi Experts,

I tried to build OWT native for android. When gclient sync finished. I use “python build_android.py” to build android dynamic library.

I encounter an error. The error information as below.

It seems gn gen failed.

I tried gn gen to generate. it dump an error

 

 

C:\owt_android\src>gn gen C:\\owt_android\\src\\out\\releasearm --args=target_os="android" is_component_build=false rtc_include_tests=false target_cpu="arm" is_debug=false rtc_use_h265=true

 

ERROR Need exactly one build directory to generate.

I expected something more like "gn gen out/foo"

You can also see "gn help gen".

 

 

=====================================================================================

Through the OWT github. There isn’t any special setting for android native. Building command as below:

Could you help to take a look this issue ?

Thanks in advance and looking forward for you response.

 

C:\owt_android\src\scripts>python build_android.py

C:\owt_android\src

bob

Namespace(debug=False, output_path='C:\\owt_android\\src\\out', target_arch='arm,arm64,x86')

bob 1

 

> args: Namespace(debug=False, output_path='C:\\owt_android\\src\\out', target_arch='arm,arm64,x86')

C:\owt_android\src\out\dist\release

bob 2

arm

bobbi

 

> generating args for arm release

boobi 1

C:\owt_android\src\out\releasearm

bobbi 2

--args=target_os="android" is_component_build=false rtc_include_tests=false target_cpu="arm" is_debug=false rtc_use_h265=true

bobbi 3

['gn', 'gen', 'C:\\owt_android\\src\\out\\releasearm', '--args=target_os="android" is_component_build=false rtc_include_tests=false target_cpu="arm" is_debug=false rtc_use_h265=true']

Traceback (most recent call last):

  File "build_android.py", line 119, in <module>

    gn_gen(arch, options.debug)

  File "build_android.py", line 36, in gn_gen

    if subprocess.call(cmd) :

  File "C:\webrtc_checkout\depot_tools\bootstrap-3_8_0_chromium_8_bin\python\bin\lib\subprocess.py", line 172, in call

    return Popen(*popenargs, **kwargs).wait()

  File "C:\webrtc_checkout\depot_tools\bootstrap-3_8_0_chromium_8_bin\python\bin\lib\subprocess.py", line 394, in __init__

    errread, errwrite)

  File "C:\webrtc_checkout\depot_tools\bootstrap-3_8_0_chromium_8_bin\python\bin\lib\subprocess.py", line 644, in _execute_child

    startupinfo)

WindowsError: [Error 2]

C:\owt_android\src\scripts>

 

Regards

Bobbi

**Comment by taste1981** [comment]
Build on windows is not supported. Please use ubuntu 18.04 for the build.

**Comment by bobbiFr** [comment]
is it supported build on MACOX?
