### ISSUE TITLE
Windows, building (un)succesfull ?

### ISSUE THREAD

**Issue by LordTrololo** [open-webrtc-toolkit/owt-client-native#546]
I am on Windows10 and I am not sure is owt being successfully compiled.

I use the following argguments:
`python build-win.py --sdk --gn_gen --arch x64 --ssl_root "C:\Program Files\OpenSSL-Win64" --msdk_root "C:\Program Files (x86)\IntelMediaSDK2021R1\Intel(R) Media SDK 2021 R1\Software Development Kit"`

Here is the output:
```
[2835/3465] CXX win_clang_x64/obj/third_party/libyuv/libyuv_internal/convert_from.obj
clang-cl: warning: unknown argument ignored in clang-cl: '-fno-delete-null-pointer-checks' [-Wunknown-argument]
[3465/3465] STAMP obj/default.stamp
Merged capi.lib
Merged dasync.lib
Merged libapps.lib
Merged libcrypto.lib
Merged libcrypto_static.lib
Merged libssl.lib
Merged libssl_static.lib
Skip libtestutil.lib
Merged openssl.lib
Skip ossltest.lib
Merged padlock.lib
Skip uitest.lib
Merged libcrypto64MD.lib
Merged libcrypto64MDd.lib
Merged libcrypto64MT.lib
Merged libcrypto64MTd.lib
Merged libssl64MD.lib
Merged libssl64MDd.lib
Merged libssl64MT.lib
Merged libssl64MTd.lib
Merged libcrypto64MD.lib
Merged libcrypto64MDd.lib
Merged libcrypto64MT.lib
Merged libcrypto64MTd.lib
Merged libssl64MD.lib
Merged libssl64MDd.lib
Merged libssl64MT.lib
Merged libssl64MTd.lib
Traceback (most recent call last):
  File "build-win.py", line 223, in <module>
    sys.exit(main())
  File "build-win.py", line 209, in main
    _mergelibs(opts.arch, opts.scheme, opts.ssl_root)
  File "build-win.py", line 122, in _mergelibs
    subprocess.call(command, cwd=HOME_PATH)
  File "C:\Git\depot_tools\bootstrap-2@3_8_10_chromium_20_bin\python\bin\lib\subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "C:\Git\depot_tools\bootstrap-2@3_8_10_chromium_20_bin\python\bin\lib\subprocess.py", line 394, in __init__
    errread, errwrite)
  File "C:\Git\depot_tools\bootstrap-2@3_8_10_chromium_20_bin\python\bin\lib\subprocess.py", line 644, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
```

Now, in the _src\out\debug-x64\obj\talk\owt_ I have the owt.lib, owt_sdk_base.lib, owt_sdk_conf.lib and owt_sdk_p2p.lib. So I am not sure **owt** is successfully compiled or not, is this `WindowsError: [Error 2] The system cannot find the file specified` a problem or not ?

**Comment by lthemep** [comment]
you will get owt-debug.lib/owt-release.lib after successfully compile in folder src\out

**Comment by LordTrololo** [comment]
When I try the following in CMD (basically I use README example):
`python3 build-win.py --gn_gen --arch x64 --scheme debug --ssl_root "C:\Program Files\OpenSSL-Win64" --msdk_root "C:\Program Files (x86)\IntelMediaSDK2021R1\Intel(R) Media SDK 2021 R1\Software Development Kit"`
I see the following output:

> Namespace(arch='x64', docs=False, gn_gen=True, msdk_root='C:\\Program Files (x86)\\IntelMediaSDK2021R1\\Intel(R) Media SDK 2021 R1\\Software Development Kit', output_path=None, quic_root=None, scheme='debug', sdk=False, ssl_root='C:\\Program Files\\OpenSSL-Win64', tests=False)
> Done. Made 952 targets from 247 files in 7081ms
> Done

But when I take a look in _src/out/debug-x64_  I cannot find any owt.lib. I can find some ninja files:
![image](https://user-images.githubusercontent.com/61494668/149552580-a28dbd5b-e3e4-4dea-9f18-20730714ed79.png)
but not the libs. And I doubt he could build the .lib in 7sec.
