### ISSUE TITLE
Build iOS framework failed, the build.py script doesn't work

### ISSUE THREAD

**Issue by qiaoxueshi** [open-webrtc-toolkit/owt-client-native#62]
Hey guys,

I wanna compile my iOS SDK, so I followed the steps described in ReadME.md:

1. git clone the code
2. `gclient sync`, the progress is successful, after sync finished, the folder is about 10G.
3. exec `scripts/build.py`, errors comes out:

```
bash-3.2$ ./build.py
./build.py: line 12: Script to build WebRTC libs.

It builds Woogeen framework which includes WebRTC lib, WooGeen base, p2p and conference
lib. By default, it builds libs for all iOS on all architecturs. You can specify
a target architectur by --arch argument.

Output framework is located in out/Woogeen.framework.
: File name too long
./build.py: line 14: import: command not found
./build.py: line 15: import: command not found
./build.py: line 16: import: command not found
./build.py: line 17: import: command not found
./build.py: line 18: import: command not found
./build.py: line 19: import: command not found
./build.py: line 20: import: command not found
./build.py: line 21: import: command not found
./build.py: line 23: syntax error near unexpected token `os.path.join'
./build.py: line 23: `sys.path.append(os.path.join(os.path.dirname(os.path.dirname(__file__)),'build','config','mac'))'
```

someone told me I should exec `python build.py` instead, when I enter this command, some other errors comes here:

```
bash-3.2$ pwd
/Users/joey/Code/RTC/src/scripts
bash-3.2$ python build.py
Traceback (most recent call last):
  File "build.py", line 24, in <module>
    import sdk_info
ImportError: No module named sdk_info
```

I searched the file in src folder and found sdk_info stays in thirdparty directory, so I copied it to scripts folder,  after executing `python build.py` again. I got anothor error:

```
➜  scripts git:(b74ee9b) ✗ python build.py                                                                       git:(b74ee9b|✚8…
Done. Made 1117 targets from 176 files in 5804ms
ninja: Entering directory `out/Debug-device-arm64'
[2573/2604] SOLINK obj/third_party/webrtc/sdk/arm64/WebRTC obj/third_party/webrtc/sdk/arm64/WebRTC.TOC
ld: warning: direct access in function 'google::protobuf::internal::ExtensionSet::MutableString(int, unsigned char, google::protobuf::FieldDescriptor const*)' from file 'obj/third_party/protobuf/libprotobuf_lite.a(extension_set.o)' to global weak symbol 'void google::protobuf::internal::arena_destruct_object<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(void*)' from file 'obj/third_party/webrtc/modules/audio_processing/aec_dump/aec_dump_impl/aec_dump_impl.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'google::protobuf::internal::ExtensionSet::MutableString(int, unsigned char, google::protobuf::FieldDescriptor const*)' from file 'obj/third_party/protobuf/libprotobuf_lite.a(extension_set.o)' to global weak symbol 'void google::protobuf::internal::arena_destruct_object<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(void*)' from file 'obj/third_party/webrtc/modules/audio_processing/aec_dump/aec_dump_impl/aec_dump_impl.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
[2604/2604] LIBTOOL-STATIC obj/talk/oms/liboms_sdk_base.a
ninja: Entering directory `out/Debug-device-arm64'
[7/7] LIBTOOL-STATIC obj/talk/oms/liboms_sdk_p2p.a
ninja: Entering directory `out/Debug-device-arm64'
[8/8] LIBTOOL-STATIC obj/talk/oms/liboms_sdk_conf.a
ninja: Entering directory `out/Debug-device-arm64'
[36/36] LIBTOOL-STATIC obj/talk/oms/liboms_sdk_objc.a
ninja: Entering directory `out/Debug-device-arm64'
[1/1] LIBTOOL-STATIC obj/talk/oms/liboms_deps.a
Traceback (most recent call last):
  File "build.py", line 202, in <module>
    sys.exit(main())
  File "build.py", line 191, in main
    dist(opts.arch, opts.scheme, opts.ssl_root)
  File "build.py", line 121, in dist
    buildwebrtcframework(arch_list, scheme)
  File "build.py", line 107, in buildwebrtcframework
    os.path.join(OUT_PATH, WEBRTC_FRAMEWORK_NAME))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dir_util.py", line 128, in copy_tree
    "cannot copy tree '%s': not a directory" % src
distutils.errors.DistutilsFileError: cannot copy tree 'out/Debug-device-arm64/WebRTC.framework': not a directory
```

I'm not familiar with Python, I do not know how to reslove this, would you please have a look at my question, and maybe modify the scripts, and make them work perfectly?  Thanks.

PS: environment:
```
➜  scripts git:(b74ee9b) ✗ python --version                                                                      git:
Python 2.7.10
➜  scripts git:(b74ee9b) ✗ uname -a                                                                              git:
Darwin xxx-MacBook-Pro.local 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64
```

**Comment by jianjunz** [comment]
> ImportError: No module named sdk_info

We saw this error when there is an error occurred during `gclient sync`.

**Comment by qiaoxueshi** [comment]
Thanks. I exec `gclient sync` again, and the following get displayed, everything seems OK.

```
➜  src git:(b74ee9b) ✗ gclient sync                                                                                                                              git:(b74ee9b|…
Syncing projects: 100% (34/34), done.

________ running '/usr/bin/python src/build/mac_toolchain.py' in '/Users/joey/Code/RTC'
Skipping Mac toolchain installation for mac
Running hooks:  48% (14/29) gn_mac
________ running 'download_from_google_storage --no_resume --platform=darwin --no_auth --bucket chromium-gn -s src/buildtools/mac/gn.sha1' in '/Users/joey/Code/RTC'
NOTICE: You have PROXY values set in your environment, but gsutil in depot_tools does not (yet) obey them.
Also, --no_auth prevents the normal BOTO_CONFIG environment variable from being used.
To use a proxy in this situation, please supply those settings in a .boto file pointed to by the NO_AUTH_BOTO_CONFIG environment var.
Running hooks:  58% (17/29) clang_format_mac
________ running 'download_from_google_storage --no_resume --platform=darwin --no_auth --bucket chromium-clang-format -s src/buildtools/mac/clang-format.sha1' in '/Users/joey/Code/RTC'
NOTICE: You have PROXY values set in your environment, but gsutil in depot_tools does not (yet) obey them.
Also, --no_auth prevents the normal BOTO_CONFIG environment variable from being used.
To use a proxy in this situation, please supply those settings in a .boto file pointed to by the NO_AUTH_BOTO_CONFIG environment var.
Running hooks:  79% (23/29) luci-go_mac
________ running 'download_from_google_storage --no_resume --platform=darwin --no_auth --bucket chromium-luci -d src/tools/luci-go/mac64' in '/Users/joey/Code/RTC'
NOTICE: You have PROXY values set in your environment, but gsutil in depot_tools does not (yet) obey them.
Also, --no_auth prevents the normal BOTO_CONFIG environment variable from being used.
To use a proxy in this situation, please supply those settings in a .boto file pointed to by the NO_AUTH_BOTO_CONFIG environment var.
Running hooks:  93% (27/29)
________ running 'download_from_google_storage --directory --recursive --num_threads=10 --no_auth --quiet --bucket chromium-webrtc-resources src/third_party/webrtc/resources' in '/Users/joey/Code/RTC'
NOTICE: You have PROXY values set in your environment, but gsutil in depot_tools does not (yet) obey them.
Also, --no_auth prevents the normal BOTO_CONFIG environment variable from being used.
To use a proxy in this situation, please supply those settings in a .boto file pointed to by the NO_AUTH_BOTO_CONFIG environment var.
Hook 'download_from_google_storage --directory --recursive --num_threads=10 --no_auth --quiet --bucket chromium-webrtc-resources src/third_party/webrtc/resources' took 19.53 secs
Running hooks: 100% (29/29)
________ running '/usr/bin/python src/scripts/prepare_dev.py' in '/Users/joey/Code/RTC'
Applying: Use OpenSSL for usrsctp
Applying: Use OpenSSL for libsrtp.
Applying: Start iOS simulator before running tests.
Applying: Remove webrtc_overrides
Applying: Fixed compile issue and disable thin archive for Linux
Applying: Adjusted jni_generator.py to fit OMS code structure.
Running hooks: 100% (29/29), done.
```

And when I  exec `python ./scripts/build.py` again, everything goes OK.

```
➜  src git:(b74ee9b) ✗ python ./scripts/build.py                git:(b74ee9b|✚1
Done. Made 1117 targets from 176 files in 1250ms
ninja: Entering directory `out/Debug-device-arm64'
ninja: no work to do.
ninja: Entering directory `out/Debug-device-arm64'
ninja: no work to do.
ninja: Entering directory `out/Debug-device-arm64'
ninja: no work to do.
ninja: Entering directory `out/Debug-device-arm64'
ninja: no work to do.
ninja: Entering directory `out/Debug-device-arm64'
ninja: no work to do.
Done. Made 1142 targets from 179 files in 3607ms
Start running unit tests.
ninja: Entering directory `out/Debug-simulator-x64'
[2721/2752] SOLINK obj/third_party/webrtc/sdk/x64/WebRTC obj/third_party/webrtc/sdk/x64/WebRTC.TOC
ld: warning: direct access in function 'google::protobuf::internal::ExtensionSet::MutableString(int, unsigned char, google::protobuf::FieldDescriptor const*)' from file 'obj/third_party/protobuf/libprotobuf_lite.a(extension_set.o)' to global weak symbol 'void google::protobuf::internal::arena_destruct_object<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(void*)' from file 'obj/third_party/webrtc/modules/audio_processing/aec_dump/aec_dump_impl/aec_dump_impl.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
[2752/2752] LIBTOOL-STATIC obj/talk/oms/liboms_sdk_base.a
ninja: Entering directory `out/Debug-simulator-x64'
[7/7] LIBTOOL-STATIC obj/talk/oms/liboms_sdk_p2p.a
ninja: Entering directory `out/Debug-simulator-x64'
[8/8] LIBTOOL-STATIC obj/talk/oms/liboms_sdk_conf.a
ninja: Entering directory `out/Debug-simulator-x64'
[36/36] LIBTOOL-STATIC obj/talk/oms/liboms_sdk_objc.a
ninja: Entering directory `out/Debug-simulator-x64'
[1/1] LIBTOOL-STATIC obj/talk/oms/liboms_deps.a
ninja: Entering directory `out/Debug-simulator-x64'
[82/82] STAMP obj/third_party/webrtc/examples/AppRTCMobile.stamp
ninja: Entering directory `out/Debug-simulator-x64'
[81/81] STAMP obj/third_party/webrtc/modules/audio_coding/audio_decoder_unittests.stamp
ninja: Entering directory `out/Debug-simulator-x64'
[64/64] STAMP obj/third_party/webrtc/common_audio/common_audio_unittests.stamp
ninja: Entering directory `out/Debug-simulator-x64'
[43/43] STAMP obj/third_party/webrtc/common_video/common_video_unittests.stamp
ninja: Entering directory `out/Debug-simulator-x64'
[110/110] STAMP obj/third_party/webrtc/modules/modules_tests.stamp
ninja: Entering directory `out/Debug-simulator-x64'
[53/53] STAMP obj/third_party/webrtc/pc/rtc_pc_unittests.stamp
ninja: Entering directory `out/Debug-simulator-x64'
[27/27] STAMP obj/third_party/webrtc/system_wrappers/system_wrappers_unittests.stamp
ninja: Entering directory `out/Debug-simulator-x64'
[52/52] STAMP obj/third_party/webrtc/test/test_support_unittests.stamp
User defaults from command line:
    IDETestRunSpecificationPath = /var/folders/8l/03cy4c716vnchk_b12kdly8h0000gn/T/EB459698-A1F1-4991-9C86-BB83AD00B752

Testing started on 'iPhone X'
2019-03-25 11:10:51.342 xcodebuild[37073:29429810]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/var/folders/8l/03cy4c716vnchk_b12kdly8h0000gn/T/A7082114-7292-4274-AB51-0364E50A5929/DerivedData/temporary/Logs/Test/Test-Transient Testing-2019.03.25_11-10-51-+0800.xcresult/1_Test/Diagnostics/audio_decoder_unittests-4125235B-06F9-4F36-BBDD-4122E386B3B6/audio_decoder_unittests-38CA061C-D090-442C-AD2F-709A4C77489F/Session-audio_decoder_unittests-2019-03-25_111051-vkhpPB.log
2019-03-25 11:10:51.343 xcodebuild[37073:29429802] [MT] IDETestOperationsObserverDebug: (F74B3201-F483-4481-B61E-7C110A5B8939) Beginning test session audio_decoder_unittests-F74B3201-F483-4481-B61E-7C110A5B8939 at 2019-03-25 11:10:51.343 with Xcode 10B61 on target <DVTiPhoneSimulator: 0x7f7f95abb4b0> {
		SimDevice: iPhone X (624529C7-3026-4CE9-84DB-FCA8475D8ADA, iOS 12.1, Shutdown)
} (12.1 (16B91))
[==========] Running 22 tests from 11 test cases.
[----------] Global test environment set-up.
[----------] 2 tests from AudioDecoderPcmUTest
[ RUN      ] AudioDecoderPcmUTest.EncodeDecode
[       OK ] AudioDecoderPcmUTest.EncodeDecode (6 ms)
[ RUN      ] AudioDecoderPcmUTest.SetTargetBitrate
[       OK ] AudioDecoderPcmUTest.SetTargetBitrate (0 ms)
[----------] 2 tests from AudioDecoderPcmUTest (7 ms total)

[----------] 2 tests from AudioDecoderPcmATest
[ RUN      ] AudioDecoderPcmATest.EncodeDecode
[       OK ] AudioDecoderPcmATest.EncodeDecode (1 ms)
[ RUN      ] AudioDecoderPcmATest.SetTargetBitrate
[       OK ] AudioDecoderPcmATest.SetTargetBitrate (0 ms)
[----------] 2 tests from AudioDecoderPcmATest (1 ms total)

[----------] 2 tests from AudioDecoderPcm16BTest
[ RUN      ] AudioDecoderPcm16BTest.EncodeDecode
[       OK ] AudioDecoderPcm16BTest.EncodeDecode (1 ms)
[ RUN      ] AudioDecoderPcm16BTest.SetTargetBitrate
[       OK ] AudioDecoderPcm16BTest.SetTargetBitrate (0 ms)
[----------] 2 tests from AudioDecoderPcm16BTest (1 ms total)

[----------] 2 tests from AudioDecoderIlbcTest
[ RUN      ] AudioDecoderIlbcTest.EncodeDecode
[       OK ] AudioDecoderIlbcTest.EncodeDecode (14 ms)
[ RUN      ] AudioDecoderIlbcTest.SetTargetBitrate
[       OK ] AudioDecoderIlbcTest.SetTargetBitrate (0 ms)
[----------] 2 tests from AudioDecoderIlbcTest (14 ms total)

[----------] 2 tests from AudioDecoderIsacFloatTest
[ RUN      ] AudioDecoderIsacFloatTest.EncodeDecode
[       OK ] AudioDecoderIsacFloatTest.EncodeDecode (15 ms)
[ RUN      ] AudioDecoderIsacFloatTest.SetTargetBitrate
[       OK ] AudioDecoderIsacFloatTest.SetTargetBitrate (0 ms)
[----------] 2 tests from AudioDecoderIsacFloatTest (15 ms total)

[----------] 2 tests from AudioDecoderIsacSwbTest
[ RUN      ] AudioDecoderIsacSwbTest.EncodeDecode
[       OK ] AudioDecoderIsacSwbTest.EncodeDecode (15 ms)
[ RUN      ] AudioDecoderIsacSwbTest.SetTargetBitrate
[       OK ] AudioDecoderIsacSwbTest.SetTargetBitrate (0 ms)
[----------] 2 tests from AudioDecoderIsacSwbTest (15 ms total)

[----------] 2 tests from AudioDecoderIsacFixTest
[ RUN      ] AudioDecoderIsacFixTest.EncodeDecode
[       OK ] AudioDecoderIsacFixTest.EncodeDecode (13 ms)
[ RUN      ] AudioDecoderIsacFixTest.SetTargetBitrate
[       OK ] AudioDecoderIsacFixTest.SetTargetBitrate (0 ms)
[----------] 2 tests from AudioDecoderIsacFixTest (13 ms total)

[----------] 2 tests from AudioDecoderG722Test
[ RUN      ] AudioDecoderG722Test.EncodeDecode
[       OK ] AudioDecoderG722Test.EncodeDecode (2 ms)
[ RUN      ] AudioDecoderG722Test.SetTargetBitrate
[       OK ] AudioDecoderG722Test.SetTargetBitrate (1 ms)
[----------] 2 tests from AudioDecoderG722Test (3 ms total)

[----------] 2 tests from AudioDecoderG722StereoTest
[ RUN      ] AudioDecoderG722StereoTest.EncodeDecode
[       OK ] AudioDecoderG722StereoTest.EncodeDecode (3 ms)
[ RUN      ] AudioDecoderG722StereoTest.SetTargetBitrate
[       OK ] AudioDecoderG722StereoTest.SetTargetBitrate (0 ms)
[----------] 2 tests from AudioDecoderG722StereoTest (3 ms total)

[----------] 2 tests from AudioDecoderOpusTest
[ RUN      ] AudioDecoderOpusTest.EncodeDecode
[       OK ] AudioDecoderOpusTest.EncodeDecode (16 ms)
[ RUN      ] AudioDecoderOpusTest.SetTargetBitrate
[       OK ] AudioDecoderOpusTest.SetTargetBitrate (1 ms)
[----------] 2 tests from AudioDecoderOpusTest (17 ms total)

[----------] 2 tests from AudioDecoderOpusStereoTest
[ RUN      ] AudioDecoderOpusStereoTest.EncodeDecode
[       OK ] AudioDecoderOpusStereoTest.EncodeDecode (8 ms)
[ RUN      ] AudioDecoderOpusStereoTest.SetTargetBitrate
[       OK ] AudioDecoderOpusStereoTest.SetTargetBitrate (1 ms)
[----------] 2 tests from AudioDecoderOpusStereoTest (9 ms total)

[----------] Global test environment tear-down
[==========] 22 tests from 11 test cases ran. (98 ms total)
[  PASSED  ] 22 tests.
2019-03-25 11:11:21.734 xcodebuild[37073:29429802] [MT] IDETestOperationsObserverDebug: 30.421 elapsed -- Testing started completed.
2019-03-25 11:11:21.737 xcodebuild[37073:29429802] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
2019-03-25 11:11:21.740 xcodebuild[37073:29429802] [MT] IDETestOperationsObserverDebug: 30.425 sec, +30.425 sec -- end
```

**Comment by qiaoxueshi** [comment]
Maybe there was some error when I exec `gclient sync` for the first time, and I didn't see it?

**Comment by showgoodjiang** [comment]
In method  buildwebrtcframework(arch_list, scheme):

Comment out these lines:
  distutils.dir_util.copy_tree(
    os.path.join(getoutputpath(arch_list[0], scheme), WEBRTC_FRAMEWORK_NAME),
    os.path.join(OUT_PATH, WEBRTC_FRAMEWORK_NAME))

Repelace them to:

  shutil.copytree(
      os.path.join('_Absolute Path of your out path_', WEBRTC_FRAMEWORK_NAME),
      os.path.join(OUT_PATH, WEBRTC_FRAMEWORK_NAME)
      )

_Absolute Path of your out path_ Sample:
/xxx/depot_tools/src/out/Debug-device-arm64

**Comment by krishnastvSMSC** [comment]
Hello Team, 

Am also facing same issue..
I did gclient sync second. 
Here is the gclient sync response..

<img width="730" alt="Screenshot 2020-11-19 at 7 34 12 PM" src="https://user-images.githubusercontent.com/45424351/99676204-35c16c00-2a9e-11eb-92ec-4d406a9db26c.png">

when I execute build.py got errors..

<img width="686" alt="Screenshot 2020-11-19 at 7 35 50 PM" src="https://user-images.githubusercontent.com/45424351/99676391-6ef9dc00-2a9e-11eb-8ddc-5b8ad1c0ff72.png">

Any one help me to resolve it.

Thank you
